title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3454018
  rhythmicContrast: 0.4373434
  brandColors: []
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: jayten
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.47336
layout_spectrum: 0.7293907
