name: jayten
favicon: null
layout_spectrum: 0.5089
typography_spectrum: 0.47336
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#717679'
    - '#ff961e'
    - '#28292e'
    - '#ec3800'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 1
purpose: []
