layout_spectrum: 0.2236842
color:
  saturation: 0
  brandStrength: 0.3454018
  lightness: 0
  rhythmicContrast: 0.4373434
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.2738095
name: jayten
